/**
 * One-off script — inserts a single DENTIST user
 * Run: node scripts/add-dentist.mjs
 *
 * - Password is hashed with bcrypt (same rounds as .env BCRYPT_ROUNDS)
 * - UUID is auto-generated by Postgres (gen_random_uuid())
 * - Safe to run multiple times — skips if the email already exists
 */

import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import bcrypt from 'bcrypt'
import knex from 'knex'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── Load .env ─────────────────────────────────────────────────────────────────
function loadEnv(envPath) {
  const raw = readFileSync(envPath, 'utf8')
  for (const line of raw.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIdx = trimmed.indexOf('=')
    if (eqIdx === -1) continue
    const key = trimmed.slice(0, eqIdx).trim()
    let val = trimmed.slice(eqIdx + 1).trim()
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1)
    }
    process.env[key] = process.env[key] ?? val
  }
}

loadEnv(resolve(__dirname, '../.env'))

// ── DB connection ─────────────────────────────────────────────────────────────
const db = knex({
  client: 'pg',
  connection: process.env.DATABASE_URL,
})

// ── Dentist user to insert — edit these values as needed ─────────────────────
const NEW_DENTIST = {
  username: 'dr.jones',
  email:    'dr.jones@smilefix.com',
  password: 'Dentist@5678',   // will be hashed — never stored in plain text
  role:     'DENTIST',
}

const BCRYPT_ROUNDS = parseInt(process.env.BCRYPT_ROUNDS ?? '12', 10)

// ── Run ───────────────────────────────────────────────────────────────────────
try {
  const existing = await db('users').where({ email: NEW_DENTIST.email }).first()

  if (existing) {
    console.log(`⚠  Skipped — ${NEW_DENTIST.email} already exists (id: ${existing.id})`)
    process.exit(0)
  }

  // Hash password with bcrypt — same library and rounds used throughout the app
  const password_hash = await bcrypt.hash(NEW_DENTIST.password, BCRYPT_ROUNDS)

  // UUID is generated by Postgres via gen_random_uuid() — no need to supply one
  const [user] = await db('users')
    .insert({
      username:      NEW_DENTIST.username,
      email:         NEW_DENTIST.email,
      password_hash,
      role:          NEW_DENTIST.role,   // must match the "Role" enum: ADMIN | DENTIST | RECEPTIONIST | ACCOUNTANT | STOREKEEPER | HR
    })
    .returning(['id', 'username', 'email', 'role', 'created_at'])

  console.log('\n✓ Dentist created successfully:\n')
  console.log(`  id       : ${user.id}`)
  console.log(`  username : ${user.username}`)
  console.log(`  email    : ${user.email}`)
  console.log(`  role     : ${user.role}`)
  console.log(`  created  : ${user.created_at}`)
  console.log(`\n  Login with: POST /api/v1/auth/login`)
  console.log(`  { "email": "${user.email}", "password": "${NEW_DENTIST.password}" }\n`)
} catch (err) {
  console.error('\n✗ Failed to insert dentist:', err.message)
  process.exit(1)
} finally {
  await db.destroy()
}
