/**
 * Migration: create notifications table
 *
 * Stores per-user in-app notifications generated by the system
 * (low inventory, appointment reminders, payment events, etc.).
 *
 * @param {import('knex').Knex} knex
 */
export async function up(knex) {
  await knex.schema.createTable('notifications', (t) => {
    t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));

    // The user this notification is for (nullable = broadcast / system-wide)
    t.uuid('user_id')
      .nullable()
      .references('id')
      .inTable('users')
      .onDelete('CASCADE')
      .onUpdate('CASCADE');

    // Notification type drives the icon / category on the frontend
    t.string('type').notNullable().defaultTo('system');   // system | appointment | inventory | finance | schedule

    // Severity maps to badge colour on the frontend
    t.string('severity').notNullable().defaultTo('info'); // error | warning | success | info | neutral

    t.string('title').notNullable();
    t.text('message').notNullable();

    // Optional deep-link destination inside the SPA
    t.string('action_label').nullable();
    t.string('action_route').nullable();

    // Arbitrary JSON payload (e.g. referenced entity ids)
    t.jsonb('metadata').nullable();

    t.boolean('is_read').notNullable().defaultTo(false);

    t.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now());
    t.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(knex.fn.now());

    t.index(['user_id']);
    t.index(['is_read']);
    t.index(['type']);
    t.index(['created_at']);
  });

  // Auto-update updated_at on every row change
  await knex.raw(`
    CREATE TRIGGER trg_notifications_updated_at
    BEFORE UPDATE ON "notifications"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at()
  `);
}

/**
 * @param {import('knex').Knex} knex
 */
export async function down(knex) {
  await knex.schema.dropTableIfExists('notifications');
}
